apiVersion: v1
kind: Service
metadata:
  name: sample-spring-boot-app-k8s-151
  labels:
    app: sample-spring-boot-app-k8s-151
    backstage.io/kubernetes-id: sample-spring-boot-app-k8s-151
spec:
  type: ClusterIP
  selector:
    app: sample-spring-boot-app-k8s-151
  ports:
    - port: 8080
      protocol: TCP
      name: http